#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.3.32f1"
#define UNITY_VERSION_DIGITS "2020.3.32"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 3
#define UNITY_VERSION_MIN 32
#define UNITY_IS_BETA 0
